example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml #sesuaikan dengan nama fungsi yang dibuat
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import membuat_task
from todolist.views import status
from todolist.views import delete
from todolist.views import show_json
from todolist.views import buat_todolist

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', membuat_task, name='membuat_task'),
    path('delete/<int:pk>', delete, name='delete'),
    path('status/<int:pk>', status, name='status'),
    path('add/', buat_todolist, name='buat_todolist'),
    path('json/', show_json, name='show_json'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MywatchlistItem(models.Model):
    title = models.CharField(max_length=255)
    release_date = models.CharField(max_length=255)
    rating = models.IntegerField()
    review = models.TextField()
    watched = models.CharField(max_length=255)

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    status = models.BooleanField(null=True, blank=True)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_barang_wishlist = CatalogItem.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Nabila Zahra Putri Awangga',
    'studentid': '2106703840',
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MywatchlistItem
from django.http import HttpResponse
from django.core import serializers

# TODO: Create your views here.
def show_mywatchlist(request):
    data_watchwishlist = MywatchlistItem.objects.all()
    context = {
    'list_barang': data_watchwishlist,
    'nama': 'Nabila Zahra Putri Awangga',
    'studentid': '2106703840',
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MywatchlistItem.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MywatchlistItem.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
import datetime
from todolist.models import Task
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.http.response import HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data = Task.objects.filter(user=request.user)
    context = {
    'todolist' : data,
    'username' :  request.user.username,
    }
    return render(request, "todolist.html", context)

# ASSIGNMENT 6
@login_required(login_url='/todolist/login/')
def show_json(request):
    task = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', task), content_type='application/json')

# @login_required(login_url='/todolist/login/')
@csrf_exempt
def buat_todolist(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        todolist = Task.objects.create(title=title, description=description, date=datetime.datetime.now(), status=False, user=request.user)

        result = {
            'fields': {
                'title' : todolist.title,
                'description' : todolist.description,
                'status' : todolist.status,
                'date' : todolist.date,
            },
            'pk' : todolist.pk
        }

    return JsonResponse(result)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) ## cek ini
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def membuat_task(request):
    if request.method == 'POST':
        title = request.POST.get('todo')
        user = request.user
        # status = False
        description = request.POST.get('description')
        date = datetime.datetime.now()
        # user = request.user
        # status = False
        Task.objects.create(title=title, description=description, date=date, user=user)
        # Task.objects.create(title=title, description=description, date=date, user=user, status=status) ## ini kalo udh ada bomus
        response = HttpResponseRedirect(reverse("todolist:show_todolist")) 
        return response

    return render(request, "task.html")


def delete(request, pk):
    data = Task.objects.get(id=pk)
    data.delete()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

def status(request, pk):
    data = Task.objects.get(id=pk)
    if data.status == False:
        data.status = True
    else:
        data.status = False
    data.save()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}
 <style>
  h1, h5, p, th, td, table {text-align: center;}
  table, th, td {
      border: 1px solid white;
      border-collapse: collapse;
      background-color: aliceblue;
    }
</style>
  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{studentid}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
    <tr>
      <td> {{barang.item_name}} </td>
      <td> {{barang.item_price}} </td>
      <td> {{barang.description}} </td>
      <td> {{barang.item_stock}} </td>
      <td> {{barang.rating}} </td>
      <td> {{barang.item_url}} </td>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}
 <style>
  h1, h5, p, th, td, table {text-align: center;}
  table, th, td {
      border: 1px solid white;
      border-collapse: collapse;
      background-color: aliceblue;
    }
</style>
  <h1>TUGAS 3 PBP</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{studentid}}</p>

  <table>
    <tr>
      <th>Title</th>
      <th>Release Date</th>
      <th>Watched</th>
      <th>Review</th>
      <th>Rating</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
    <tr>
      <td> {{barang.title}} </td>
      <td> {{barang.release_date}} </td>
      <td> {{barang.watched}} </td>
      <td> {{barang.review}} </td>
      <td> {{barang.rating}} </td>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>
<p>
  
</p>

</html>

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

<title>Login</title>
{% endblock meta %}

{% block content %}


<div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
    <div class = "p-4 w-full max-w-sm rounded-4 border border-gray-200 shadow-md sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700" style="background-color: rgb(133, 218, 252)">
        <h1 class="text-white">Login</h1>
        <form method="POST" action="">
        {% csrf_token %}
            <div class="text-xl font-medium text-gray-900 light:text-white">
                <label for="username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your email</label>
                <input type="username" name="username" id="username" placeholder="Username" class="form-control">
            </div>
            <div>
                <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your password</label>
                <input type="password" name="password" placeholder="Password" class="form-control">
            </div>
            <div class="flex items-start justify-content-center mt-3">
                <input type="submit" value="Login" class="btn btn-outline-light">
            <div class="text-sm font-medium text-gray-500 dark:text-gray-300">
                Belum mempunyai akun? <a href="{% url 'todolist:register' %}" class = "text-white">Buat Akun</a>
            </div>
        </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     

    </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>


<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
    <div class = "login rounded-4 p-4 text-gray-300" style="background-color: rgb(133, 218, 252);">
        <h1>Formulir Registrasi</h1>  

            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}

    </div>  
</div>

{% endblock content %}

todolist/templates/task.html
{% extends 'base.html' %}

{% block meta %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

<nav class="navbar navbar-expand-lg bg-light p-3" style="padding: 13px;" >

    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <button type="button" class="btn" style="background-color: rgb(85, 89, 90)">
                    <a class="text-decoration-none text-white" href="{% url 'todolist:show_todolist' %}">Home</a>
                </button>
                </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
              <li class="nav-item">
              <button type="button" class="btn" style="background-color: rgb(85, 89, 90)">
                  <a class="text-decoration-none text-white" href="{% url 'todolist:logout' %}">Logout</a>
              </button>
              </li>
            </ul>
        </div>
    </div>
  </nav>

<style>
    title, h1, th, td, table {text-align: center;}
    table, th, td {
        border-collapse: collapse;
        background-color: rgb(250, 227, 17);
        border-width: 1px;
        padding: 20px;
        /* border-radius: 10px; */
      }
    * {
        font-family: 'Arial';
        text-align: center;
        vertical-align: middle;
    }
    th, td {
        padding: 10px 14px
    }
    table {
    margin-left: auto;
    margin-right: auto;
    }
  </style>

<title>Add Task</title>
{% endblock meta %}

{% block content %}

<div class = "create_task">

    <br>
    <br>

    <h3>Tambah Task Baru!</h3>
    <br>
    <br>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Todo: </td>
                <td><input type="text" name="todo" placeholder="Isi Todo" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td><input type="text" name="description" placeholder="Deskripsi Todo" class="form-control"></td>
            </tr>
        </table>
        <br>
        <input type="submit" name="submit" value="Tambah Task"/>
    </form>

</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </body>
</html>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" /> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
  $(document).ready(function() {
    $.get("/todolist/json/", function(data) {
      console.log(data)
      for (i = 0; i < data.length; i++) {
        // console.log(data)
        $("#todolist").append(`<div class="card">
        <div class="card-header text-gray-300" style="background-color: rgb(250, 227, 17);">
          <h5 class="card-title">${data[i].fields.title}</h5>
        </div>
        <div class="card-body" style="background-color: rgb(238, 238, 238);">
          <p>Date added: ${data[i].fields.date}</p>
          <p>Detail: ${data[i].fields.description}</p>
        </div>
      </div>`)
      }
  });
// });
  $("#modal").click(function() {
    console.log("something")
    $.post("/todolist/add/", {
      title: $("#title").val(),
      description: $("#description").val()},
      function(result) {
        console.log("cek")
        $("#todolist").append(
        `<div class="card">
          <div class="card-header text-gray-300" style=" background-color: rgb(250, 227, 17);">
            <h5 class="card-title">${result.fields.title}</h5>
          </div>
          <div class="card-body" style="background-color: rgb(238, 238, 238);">
            <p>Date added: ${result.fields.date}</p>
            <p>Detail: ${result.fields.description}</p>
          </div>
        </div>`)
      }
    )
    })
  });
</script>

<style>
  .card:hover{
    transform: scale(1);
    box-shadow: 0 10px 20px rgba(0, 0, 0, .12), 0 4px 8px rgba(0, 0, 0, .06);
  }
  .card {
    border: transparent;
  }
</style>


<nav class="navbar navbar-expand-lg bg-light p-3" style="padding: 13px;" >

  <div class="container-fluid">
      <a class="navbar-brand" href="#"> Hello, {{username}}!</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <button type="button" class="btn" style="background-color: rgb(85, 89, 90)">
                  <!-- <a class="text-decoration-none text-white" href="{% url 'todolist:membuat_task' %}">Create New Task</a> -->
                  <a class="text-decoration-none text-white" data-bs-toggle="modal" data-bs-target="#createTaskModal">Add Task<span class="sr-only navbar-dark bg-dark"></span></a>
              </button>
              </li>
          </ul>
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
            <button type="button" class="btn" style="background-color: rgb(85, 89, 90)">
                <a class="text-decoration-none text-white" href="{% url 'todolist:logout' %}">Logout</a>
            </button>
            </li>
          </ul>
      </div>
  </div>
</nav>

<div class="div m-4 d-flex justify-content-center">
  <h4>
    {{mess}}
  </h4>
</div>

<div class="div m-4 d-flex justify-content-center">
  <h4>
    <p>This is your todolist!</p>
  </h4>
</div>

<div class="modal fade" id="createTaskModal" tabindex="-1" role="dialog" aria-labelledby="createTaskModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color: rgb(85, 89, 90);">
      <div class="modal-header text-gray-300" style="background-color: rgb(238, 238, 238);">
        <h5 class="modal-title text-gray-300">Add Your New Task!</h5>
      </div>
      <div class="modal-body" style="background-color: rgb(238, 238, 238);">
        {% csrf_token %}
        <label class="text-gray-300 font-bold">Title</label>
        <input id="title" type="title" name="title" placeholder="Task Title">
        <br>
        <br>
        <label class="text-gray-300 font-bold">Description</label>
        <input id="description" type="description" name="description" placeholder="Task Description">
      </div>
      <div class="modal-footer" style="background-color: rgb(238, 238, 238);">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="modal">Add</button>
      </div>
    </div>
  </div>
</div>

 <div class="container-fluid">
   <div class="row row-cols-1 row-cols-md-3 g-4 mx-5" id="todolist">
  </div>
</div>
     <!-- {% for todo in todolist %}
     <div class="col">
       <div class="card">
         <div class="card-header text-gray-300" style="background-color: rgb(250, 227, 17);">
           <h5 class="card-title">{{todo.title}}</h5>
         </div>
         <div class="card-body" style="background-color: rgb(238, 238, 238);">
//           <p>Date added: {{todo.date}}</p>
//           <p>Detail: {{todo.description}}</p>
//           <p>
//             Status : 
//             {% if todo.status %}
//             Finished
//             {% else %}
//             Not Yet
//             {% endif %}
//           </p>
//           <div class="row">
//             <div class="col">
//               <a href="{% url 'todolist:status' todo.id %}" class="btn btn-primary">Change Status</a>
//             </div>
//             <div class="col d-flex justify-content-end">
//               <a href="{% url 'todolist:delete' todo.id %}" class="btn btn-danger">Delete Task</a>
//             </div>
//           </div>
//         </div>
//       </div>
//       {% endfor %} -->
<!-- //     </div> -->
  <!-- </div>
 </div> -->

{% endblock content %}